# Generated by Django 5.1.3 on 2024-11-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendancesystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collegeday",
            name="class_obj",
        ),
        migrations.RemoveField(
            model_name="collegeday",
            name="students",
        ),
        migrations.AddField(
            model_name="collegeday",
            name="classes",
            field=models.ManyToManyField(
                blank=True, related_name="college_days", to="attendancesystem.class"
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendancesystem.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendancesystem.student",
                    ),
                ),
            ],
        ),
    ]
