# Generated by Django 5.1.3 on 2024-11-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendancesystem", "0003_alter_class_lecturer_alter_lecturer_dob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="collegeday",
            constraint=models.UniqueConstraint(
                fields=("date",), name="unique_college_day_per_class"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendancesystem.class",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="college_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendancesystem.collegeday",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendancesystem.student",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student_attended",
            field=models.ManyToManyField(
                blank=True,
                related_name="attended_classes",
                to="attendancesystem.student",
            ),
        ),
    ]
