# Generated by Django 5.1.3 on 2024-11-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendancesystem", "0004_attendancerecord_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendanceRecord",
        ),
    ]
