# Generated by Django 5.1.3 on 2024-11-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendancesystem", "0005_delete_attendancerecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collegeday",
            name="unique_college_day_per_class",
        ),
        migrations.RemoveField(
            model_name="collegeday",
            name="classes",
        ),
        migrations.AddField(
            model_name="collegeday",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendancesystem.class",
            ),
        ),
        migrations.AddField(
            model_name="collegeday",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="attended_classes",
                to="attendancesystem.student",
            ),
        ),
    ]
